### ISSUE TITLE
RFC: Remove helpers

### ISSUE THREAD

**Issue by pvinis** [artsy/cohesion#212]
The main suggestion here is to remove helpers from cohesion and pull them in the clients if they want to use them.

The usefulness of cohesion is the fact that it provides types and interfaces to make sure we send the right data to our analytics. How do that per client shouldn't matter to cohesion. It also makes PRs harder to create, as we need to have an engineer help make these helpers, before we even have the chance to use them, so the final look of a helper is still uncertain.

By removing the helpers from cohesion, we can allow for it to be owned by data team way more cleanly. It also allows the clients to decide how they want to handle sending. The types/interfaces are what data team needs, and what the clients can obey.

## Reasoning

It seems like the helpers of cohesion are a cause of duplication and confusion. There have been a few times already where helpers are not used and are duplicated in the clients, or times were there are no helpers created.

- `share`
The [share helper here](https://github.com/artsy/cohesion/blob/master/src/Helpers/Share.ts) was created, and in the end it's [not used](https://github.com/artsy/eigen/blob/master/src/lib/Scenes/Artwork/Components/ArtworkHeader.tsx#L188-L203).

- `tappedShowMore`
[See here](https://github.com/artsy/cohesion/search?q=tappedShowMore) that cohesion has no helper, and eigen just uses [its own here](https://github.com/artsy/eigen/blob/7ae0c7e8aaa37ad78b4e3ffe9388cc3a15740e27/src/lib/Scenes/MyCollection/Screens/Artwork/Components/MyCollectionArtworkMeta.tsx#L102-L114).

There are more examples of this, I quickly found these for now.

For the first one, I remember adding this while being unsure how we will use this, and turns out it's easier to have two helpers, one for the native ios share, one for the new default, custom share. Cohesion doesn't need to know that. It's enough if both eigen helpers send the right things needed, based on the schema/types/interfaces.

The second one is one of the many examples where an engineer either was not available, or was unsure, or just didn't need to add a helper at that point. It works well.

As an extra, eigen already has an established way to do tracking [documented here](https://github.com/artsy/eigen/blob/7ae0c7e8aaa37ad78b4e3ffe9388cc3a15740e27/docs/analytics_and_tracking.md) using local helpers that can either live in the component file, or in a helper file if they are more general.

Edit: As @sweir27 accurately pointed out in a comment below, these helpers are not actually shared. force and eigen have their own. So it makes helpers even less neccessary to live within cohesion.

## Exceptions:

No exceptions. `Helpers` dir is deleted.

## Additional Context:

You can see the discussion that started our meeting with the above resulting RFC [in slack here](https://artsy.slack.com/archives/C015KTU8RQT/p1620834725030900).

After that, @sweir27, @abhitip and I had a meeting and discussed a bunch of that. We came to the conclusion that helpers could be removed. That would help cohesion be cleaner, more owned by the data team for changes, and clients can do their custom functions freely and more consistently.

## How this RFC is resolved

- Remove the `Helpers` dir in cohesion, and publish a new version
- eigen and force stop using the helpers from cohesion, and they keep using their own functions or if they used some cohesion helpers, these can be copied over to the client repos. (That could be done in a mob session or two, scheduled on a Future Friday.)
- Update the eigen docs to remove the reference to helpers from cohesion.

We'll collect feedback on this RFC from the team for a week. We'll consider this RFC approved
if 50% of the engineering team actively approves of this change. Add a 👍 or 👎  reaction to
this proposal to vote.

**Comment by kajatiger** [comment]
Since I had never worked in cohesion, I am very neutral about this and will leave it to the people who know more.

**Comment by sweir27** [comment]
It would be worth making explicit in the "reasoning" section that helpers are primarily used within single apps (i.e. we don't share helpers across Eigen and force, as far as I know).

Thanks for writing this up!

**Comment by damassi** [comment]
Helpers are definitely confusing. I know when I first started using cohesion I had a lot of similar questions [around this timestamp]((https://artsy.slack.com/archives/C015KTU8RQT/p1605052735007300)), and then started thinking that we could largely just automate stuff. Eve's explanation that helpers should only be used when there's some kind of behavior that a) can be shared; and b) needs to be augmented before being dispatched to segment, made me realize that helpers themselves are ideally rare additions specifically around pre-processing. This isn't clear however, and devs are often just defining simple objects that are wrapped in a function and importing that where needed (instead of just composing interface props locally). 

This confusion has come up again and again, where if it was just a store of interfaces shared across various platforms it would be simpler. 

All that said, since helpers are currently being used all over it would require a good amount of dev time to replace everything across call-sites and migrate.

A couple thoughts: 

1. We should find a co-sponsor on web that would agree to help with the migration; since Palette v3 is heating up it'd be an undue burden to expect the RFC author to then refactor web and mobile 
1. Alternatively, we rename helpers -> `deprecatedHelpers` and then we can do a find-and-replace in consuming apps
1. And with 2, we could add a Danger rule preventing additions to the helpers folder (this doesn't help with understanding, though). If devs try to add, it points them to instructions about how to use the lib.

**Comment by pvinis** [comment]
I do like the idea of someone else throwing their name here that would like to help me do this for force.

The `deprecatedHelpers` idea with danger seems good. For eigen we don't really need it, we use the helpers in not too many places. I think even in force it might not be too much extra work to search and replace the helpers used to an import from a local folder, but I'm fine to go either way.

**Comment by mdole** [comment]
Good call! I was also confused by the helpers, and it seems like it's a pattern that we used when we first created Cohesion but moved away from when we realized it wasn't super helpful. Maybe this would be a good thing for a new-ish dev (or a few devs) to help with who wants to get familiar with tracking!

**Comment by pvinis** [comment]
## Resolution
We decided to do it.

## Level of Support
2: Positive feedback.

#### Additional Context:
People agree that helpers are confusing, and we should allow the data team to own the cohesion schema more wholly.

## Next Steps
- [ ] Find one more person to help with force and I work on eigen.
- [ ] Remove the `helpers` (or rename them and deprecated them. We will decide with whoever helps with force).
- [ ] Deploy a new major version of cohesion.
- [ ] Do the necessary changes in force and eigen.
